import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { FiActivity, FiArrowRight, FiAward, FiBookOpen, FiClock, FiHelpCircle, FiLoader, FiPlayCircle, FiTarget } from "react-icons/fi";
import { getDashboard } from "../services/api";
import { useToast } from "../components/ToastProvider";

const DashboardPage = () => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const { pushToast } = useToast();
  useEffect(() => { getDashboard().then((response) => setData(response.data)).catch(() => pushToast("Unable to load dashboard data", "error")).finally(() => setLoading(false)); }, [pushToast]);
  const progress = data?.progress || {};
  const path = data?.learning_path || {};
  const attempts = data?.quiz_attempts || [];
  const pending = data?.pending_topics || [];
  const leaderboard = data?.leaderboard || [];
  const currentRank = data?.current_rank;
  return <div className="space-y-6 p-6 lg:p-8">
    <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-cyan-500/10 via-slate-900 to-violet-500/10 p-8"><p className="text-sm uppercase tracking-[0.3em] text-cyan-300">Student dashboard</p><h1 className="mt-2 text-3xl font-semibold text-white">{data?.welcome || "Welcome back"}</h1><p className="mt-3 text-slate-300">Your learning progress, next activity, and support tools in one place.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/generate" className="inline-flex items-center gap-2 rounded-full bg-cyan-500 px-4 py-2 font-semibold text-slate-950">{path.title ? "Update roadmap" : "Create roadmap"}<FiArrowRight /></Link><Link to="/quiz" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-slate-200"><FiPlayCircle /> Take quiz</Link><Link to="/assistant" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-slate-200"><FiHelpCircle /> Ask AI</Link></div></div>
    {loading ? <div className="flex min-h-40 items-center justify-center rounded-[32px] border border-white/10 bg-slate-900/70 text-slate-400"><FiLoader className="mr-2 animate-spin" /> Loading your learning data...</div> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Progress", `${Math.round(progress.overall_progress || 0)}%`, FiTarget], ["Streak", `${progress.current_streak || 0} days`, FiActivity], ["Weekly hours", `${progress.weekly_hours || 0} hrs`, FiClock], ["XP points", `${progress.xp_points || 0}`, FiAward], ["Quiz attempts", `${attempts.length}`, FiBookOpen]].map(([label, value, Icon]) => <motion.div key={label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="rounded-3xl border border-white/10 bg-slate-900/70 p-5"><Icon className="text-cyan-300" /><p className="mt-4 text-sm text-slate-400">{label}</p><p className="text-2xl font-semibold text-white">{value}</p></motion.div>)}</div>
      <div className="grid gap-6 xl:grid-cols-[1.1fr,0.9fr]"><section className="rounded-[32px] border border-white/10 bg-slate-900/70 p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-cyan-300">Current learning path</p><h2 className="mt-1 text-xl font-semibold text-white">{path.title || "No roadmap yet"}</h2></div><Link to="/generate" className="text-sm text-cyan-200">Open path</Link></div>{path.title ? <><div className="mt-5 h-3 rounded-full bg-white/10"><div className="h-3 rounded-full bg-gradient-to-r from-cyan-400 to-violet-400" style={{ width: `${Math.min(100, progress.overall_progress || 0)}%` }} /></div><p className="mt-2 text-sm text-slate-400">{progress.tasks_completed || 0} completed of {(path.tasks || []).length} tracked topics</p><div className="mt-5 space-y-2">{pending.slice(0, 4).map((topic) => <div key={topic} className="rounded-xl bg-white/5 p-3 text-sm text-slate-300">Next: {topic}</div>)}</div></> : <p className="mt-5 text-slate-400">Generate a personalized path to begin tracking topics.</p>}</section><section className="rounded-[32px] border border-white/10 bg-slate-900/70 p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-white">Student leaderboard</h2><span className="text-sm text-amber-200">{currentRank ? `Rank #${currentRank}` : "Unranked"}</span></div><div className="mt-5 space-y-2">{leaderboard.slice(0, 5).map((entry, index) => <div key={entry.username} className="flex items-center justify-between rounded-xl bg-white/5 p-3"><span className="text-slate-300">#{index + 1} {entry.full_name || entry.username}</span><span className="text-cyan-200">{entry.xp_points || 0} XP</span></div>)}{!leaderboard.length && <p className="text-sm text-slate-400">Complete activities to appear here.</p>}</div></section></div>
      <div className="grid gap-6 xl:grid-cols-3"><Link to="/quiz" className="rounded-[28px] border border-white/10 bg-amber-500/10 p-6 transition hover:border-amber-300/40"><FiPlayCircle className="text-amber-200" /><h2 className="mt-4 text-xl font-semibold text-white">Take a quiz</h2><p className="mt-2 text-sm text-slate-300">Practice your domain and update your quiz performance.</p></Link><Link to="/assistant" className="rounded-[28px] border border-white/10 bg-violet-500/10 p-6 transition hover:border-violet-300/40"><FiHelpCircle className="text-violet-200" /><h2 className="mt-4 text-xl font-semibold text-white">AI Assistant</h2><p className="mt-2 text-sm text-slate-300">Get a simple explanation or escalate an unresolved doubt.</p></Link><Link to="/chat" className="rounded-[28px] border border-white/10 bg-cyan-500/10 p-6 transition hover:border-cyan-300/40"><FiAward className="text-cyan-200" /><h2 className="mt-4 text-xl font-semibold text-white">Chat with Admin</h2><p className="mt-2 text-sm text-slate-300">Continue a saved conversation with your learning team.</p></Link></div>
    </>}
  </div>;
};

export default DashboardPage;